language: nix
os:
  - linux
  - osx

jobs:
  include:
    - stage: test
      script:
        - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
        - mkdir -p ~/.config/nixpkgs
        - echo "{}" > ~/.config/nixpkgs/home.nix
        - nix-shell . -A install
    - script:
        - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
        - mkdir -p ~/.config/nixpkgs
        - echo "{...}: {}" > ~/.config/nixpkgs/home.nix
        - nix-shell . -A install
